/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum Fail2BanEvent {
  Found = 0,
  Ban = 1,
  Unban = 2,
  Restore = 3,
  Ignore = 4,
  AlreadyBanned = 5,
  Failed = 6,
  Unknown = 7
}

export declare const enum Fail2BanHeaderType {
  Filter = 0,
  Actions = 1,
  Server = 2
}

export declare const enum Fail2BanLevel {
  Info = 0,
  Notice = 1,
  Warning = 2,
  Error = 3,
  Debug = 4
}

export interface Fail2BanLog {
  timestamp?: string
  header?: Fail2BanHeaderType
  pid?: number
  level?: Fail2BanLevel
  jail?: string
  event?: Fail2BanEvent
  ip?: string
}

export declare function parse(input: string): [Array<Fail2BanLog>, Array<ParseError>]

export interface ParseError {
  lineNumber: number
  line: string
}
