.PHONY: build build-debug test bench format lint install

PNPM := pnpm

build:
	$(PNPM) build

build-debug:
	$(PNPM) build:debug

test:
	$(PNPM) test

bench:
	$(PNPM) bench

format:
	$(PNPM) format

lint:
	$(PNPM) lint

install:
	$(PNPM) install
