from enum import Enum
from typing import Optional

class HeaderType(Enum):
    """Fail2ban log header type."""

    Filter = ...
    Actions = ...
    Server = ...

class Level(Enum):
    """Fail2ban log level."""

    Info = ...
    Notice = ...
    Warning = ...
    Error = ...
    Debug = ...

class Event(Enum):
    """Fail2ban event type."""

    Found = ...
    Ban = ...
    Unban = ...
    Restore = ...
    Ignore = ...
    AlreadyBanned = ...
    Failed = ...
    Unknown = ...

class Fail2BanLog:
    """A parsed fail2ban log line."""

    @property
    def timestamp(self) -> Optional[str]:
        """RFC 3339 timestamp string, or None if not present."""
        ...
    @property
    def header(self) -> Optional[HeaderType]:
        """Log header type."""
        ...
    @property
    def pid(self) -> Optional[int]:
        """Process ID from the log line."""
        ...
    @property
    def level(self) -> Optional[Level]:
        """Log level."""
        ...
    @property
    def jail(self) -> Optional[str]:
        """Jail name (e.g. ``"sshd"``)."""
        ...
    @property
    def event(self) -> Optional[Event]:
        """Event type."""
        ...
    @property
    def ip(self) -> Optional[str]:
        """IP address string (IPv4 or IPv6), or None if not parseable."""
        ...
    def __repr__(self) -> str: ...

class ParseError:
    """A parse error for a single log line."""

    @property
    def line_number(self) -> int:
        """1-based line number where the error occurred."""
        ...
    @property
    def line(self) -> str:
        """The raw line that failed to parse."""
        ...
    def __repr__(self) -> str: ...

def parse(input: str) -> tuple[list[Fail2BanLog], list[ParseError]]:
    """Parse fail2ban log input and return both logs and errors.

    Args:
        input: A string containing one or more fail2ban log lines.

    Returns:
        A tuple ``(logs, errors)`` where *logs* is a list of
        :class:`Fail2BanLog` and *errors* is a list of :class:`ParseError`.
    """
    ...
